# Python to Linux Web App on Azure
# Build your Python project and deploy it to Azure as a Linux Web App.
# Change python version to one that's appropriate for your application.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: '8894ecec-258d-494f-b1b5-19d2ddb0569b'

  # Web app name
  webAppName: 'flasksklearn-app'

  # Agent pool name
  agentPoolName: 'AgentPool'

  # Environment name
  environmentName: 'flasksklearn-app'

  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)
  
  # Python version: 3.9
  pythonVersion: '3.9'

stages:
- stage: Build
  displayName: Build and Lint Application
  jobs:
  - job: BuildJob
    displayName: Build Job
    pool:
      name: $(agentPoolName)
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'

    - script: |
        sudo apt update
        sudo apt install -y make
      displayName: "Install make utility"

    - script: |
        python3.9 -m venv myrepo2
        source myrepo2/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      workingDirectory: $(projectRoot)
      displayName: "Install requirements"

    - script: |
        source myrepo2/bin/activate
        make install
        make lint
      workingDirectory: $(projectRoot)
      displayName: "Run Lint test"
      
    - script: |
        sudo apt-get update
        sudo apt-get install -y zip
      displayName: 'Install zip utility'
  
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Publish Build Artifact'
      artifact: drop

- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    displayName: Deploy Application
    pool:
      name: $(agentPoolName)
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
            displayName: 'Use Python version'

          - task: AzureWebApp@1
            displayName: 'Deploy to Azure Web App: $(webAppName)'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appName: $(webAppName)
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
